####################################################################
# server 選擇運行哪一個環境
####################################################################
spring:
  context-path: /
  profiles:
    include: quartz
    active: dev

